import React from 'react'
import { RouterProvider, createRouter } from '@tanstack/react-router'
// This file will be generated by the router plugin
// @ts-expect-error: routeTree.gen is generated at runtime
import { routeTree } from './routeTree.gen'
import './App.css'

// Create a new router instance
const router = createRouter({ routeTree })

// Register the router instance for type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

const App: React.FC = () => {
  return (
    <RouterProvider router={router} />
  )
}

export default App
