/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditorTestBedRouteImport } from './routes/editor-test-bed'
import { Route as IndexRouteImport } from './routes/index'

const EditorTestBedRoute = EditorTestBedRouteImport.update({
  id: '/editor-test-bed',
  path: '/editor-test-bed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor-test-bed': typeof EditorTestBedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor-test-bed': typeof EditorTestBedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor-test-bed': typeof EditorTestBedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor-test-bed'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor-test-bed'
  id: '__root__' | '/' | '/editor-test-bed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorTestBedRoute: typeof EditorTestBedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/editor-test-bed': {
      id: '/editor-test-bed'
      path: '/editor-test-bed'
      fullPath: '/editor-test-bed'
      preLoaderRoute: typeof EditorTestBedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorTestBedRoute: EditorTestBedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
